### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by HarryLee186** [Josh-G/zabbix-slack-node#1]
Don't suppose you'd point me in the right direction on how to set this up? Is it as simple as importing a script in Zabbix or do I also need to install Node on the (zabbix)server?

**Comment by Josh-G** [comment]
i will update the README shortly to describe how to configure zabbix use it

unfortunately it does require the installation of node, and using `npm` to grab some further dependencies

**Comment by HarryLee186** [comment]
🙌🙌 Thanks & yeah no worries just a bit unsure how exactly to go about it all really.
